apiVersion: apps/v1
kind: Deployment
metadata:
  name: yapi
  labels:
    app: yapi
spec:
  selector:
    matchLabels:
      app: yapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: yapi
    spec:
      containers:
      - name: yapi
        image: registry.cn-hangzhou.aliyuncs.com/anoy/yapi
        ports:
        - containerPort: 3000
        workingDir: /api/vendors
        args:
          - server/app.js
        volumeMounts:
          - mountPath: /api/config.json
            name: yapi-config
            subPath: config.json
      volumes:
        - name: yapi-config
          configMap:
            name: yapi-config
            items:
              - key: config.json
                path: config.json