# 创建部署
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  labels:
    app: artifactory
spec:
  selector:
    matchLabels:
      app: artifactory
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      containers:
      - name: artifactory
        image: docker.bintray.io/jfrog/artifactory-oss
        ports:
        - containerPort: 8081
        volumeMounts:
          - mountPath: /var/opt/jfrog/artifactory
            name: artifactory-volume
      volumes:
        - name: artifactory-volume
          persistentVolumeClaim:
            claimName: artifactory-pvc
---
# 创建服务
apiVersion: v1
kind: Service
metadata:
  name: artifactory
  labels:
    app: artifactory
spec:
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 31114
  selector:
    app: artifactory
  type: NodePort
