# 创建部署
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  labels:
    app: artifactory
spec:
  selector:
    matchLabels:
      app: artifactory
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      containers:
      - name: artifactory
        image: docker.bintray.io/jfrog/artifactory-oss
        ports:
        - containerPort: 8081
        volumeMounts:
          - mountPath: /var/opt/jfrog/artifactory
            name: artifactory-volume
      volumes:
        - name: artifactory-volume
          persistentVolumeClaim:
            claimName: artifactory-pvc