apiVersion: v1
kind: Service
metadata:
  name: artifactory
  labels:
    app: artifactory
spec:
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 31114
  selector:
    app: artifactory
  type: NodePort
