apiVersion: v1
kind: Service
metadata:
  name: micro-core-gateway
  labels:
    app: micro-core-gateway
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000
  selector:
    app: micro-core-gateway
  type: NodePort