apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-auth-config
data:
  config.json: '{
                	"auths": {
                		"registry.cn-hangzhou.aliyuncs.com": {
                			"auth": "MjI4NzAxOTkyQHFxLmNvbTphbm95aS5jb20="
                		}
                	},
                	"HttpHeaders": {
                		"User-Agent": "Docker-Client/17.12.1-ce (linux)"
                	}
                }'
