apiVersion: batch/v1
kind: Job
metadata:
  name: jenkins-git-init
spec:
  template:
    spec:
      containers:
      - name: jenkins-git-init
        image: busybox
        command:
          - sh
        args: ["-c", "sleep 5 && chown -Rc 0 /var/jenkins_home/workspace/*/.git"]
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-volume
      restartPolicy: Never
      volumes:
        - name: jenkins-volume
          persistentVolumeClaim:
            claimName: jenkins-pvc
  backoffLimit: 1