# 创建服务
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31115
#  保留此端口号，Maybe it is useful in the future
#  - port: 50000
#    targetPort: 50000
#    nodePort: 31116
  selector:
    app: jenkins
  type: NodePort