# 创建服务
apiVersion: v1
kind: Service
metadata:
  name: micro-core-scca
  labels:
    app: micro-core-scca
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31118
  selector:
    app: micro-core-scca
  type: NodePort